export const metadata = {
    title: "layot",
    description: 'Generated by create next app',
  }

const  SingleProductLayout= async ({children, params})=> {
  


    

   

    
    return(
        <section className="single-product-page bg-white">
            {children}
        </section>
    )

}
export default SingleProductLayout;