import { Inter } from 'next/font/google'
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CartContextProvider from './context/Cart';
import CountProvider from './context/Count';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopping',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <CountProvider>
      <CartContextProvider>
      <html lang='en' >
        <body className={`${inter.className} bg-gray-900 text-slate-50`}>
        <Header />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </html>
      </CartContextProvider>
    </CountProvider>
  )
}
