export const metadata = {
    title: 'Products',
    description: 'Generated by create next app',
  }

function ProductsPageLayout({children}) {
    

    return(
        <section className='products-page'>
            {children}
        </section>
    )
}
export default ProductsPageLayout;